
INSERT INTO SCHEMA_TRACING.tag_key (id, key, tag_type)
OVERRIDING SYSTEM VALUE
VALUES
    (1, 'service.name', SCHEMA_TRACING.resource_tag_type()),
    (2, 'service.namespace', SCHEMA_TRACING.resource_tag_type()),
    (3, 'service.instance.id', SCHEMA_TRACING.resource_tag_type()),
    (4, 'service.version', SCHEMA_TRACING.resource_tag_type()),
    (5, 'telemetry.sdk.name', SCHEMA_TRACING.resource_tag_type()),
    (6, 'telemetry.sdk.language', SCHEMA_TRACING.resource_tag_type()),
    (7, 'telemetry.sdk.version', SCHEMA_TRACING.resource_tag_type()),
    (8, 'telemetry.auto.version', SCHEMA_TRACING.resource_tag_type()),
    (9, 'container.name', SCHEMA_TRACING.resource_tag_type()),
    (10, 'container.id', SCHEMA_TRACING.resource_tag_type()),
    (11, 'container.runtime', SCHEMA_TRACING.resource_tag_type()),
    (12, 'container.image.name', SCHEMA_TRACING.resource_tag_type()),
    (13, 'container.image.tag', SCHEMA_TRACING.resource_tag_type()),
    (14, 'faas.name', SCHEMA_TRACING.resource_tag_type()),
    (15, 'faas.id', SCHEMA_TRACING.resource_tag_type()),
    (16, 'faas.version', SCHEMA_TRACING.resource_tag_type()),
    (17, 'faas.instance', SCHEMA_TRACING.resource_tag_type()),
    (18, 'faas.max_memory', SCHEMA_TRACING.resource_tag_type()),
    (19, 'process.pid', SCHEMA_TRACING.resource_tag_type()),
    (20, 'process.executable.name', SCHEMA_TRACING.resource_tag_type()),
    (21, 'process.executable.path', SCHEMA_TRACING.resource_tag_type()),
    (22, 'process.command', SCHEMA_TRACING.resource_tag_type()),
    (23, 'process.command_line', SCHEMA_TRACING.resource_tag_type()),
    (24, 'process.command_args', SCHEMA_TRACING.resource_tag_type()),
    (25, 'process.owner', SCHEMA_TRACING.resource_tag_type()),
    (26, 'process.runtime.name', SCHEMA_TRACING.resource_tag_type()),
    (27, 'process.runtime.version', SCHEMA_TRACING.resource_tag_type()),
    (28, 'process.runtime.description', SCHEMA_TRACING.resource_tag_type()),
    (29, 'webengine.name', SCHEMA_TRACING.resource_tag_type()),
    (30, 'webengine.version', SCHEMA_TRACING.resource_tag_type()),
    (31, 'webengine.description', SCHEMA_TRACING.resource_tag_type()),
    (32, 'host.id', SCHEMA_TRACING.resource_tag_type()),
    (33, 'host.name', SCHEMA_TRACING.resource_tag_type()),
    (34, 'host.type', SCHEMA_TRACING.resource_tag_type()),
    (35, 'host.arch', SCHEMA_TRACING.resource_tag_type()),
    (36, 'host.image.name', SCHEMA_TRACING.resource_tag_type()),
    (37, 'host.image.id', SCHEMA_TRACING.resource_tag_type()),
    (38, 'host.image.version', SCHEMA_TRACING.resource_tag_type()),
    (39, 'os.type', SCHEMA_TRACING.resource_tag_type()),
    (40, 'os.description', SCHEMA_TRACING.resource_tag_type()),
    (41, 'os.name', SCHEMA_TRACING.resource_tag_type()),
    (42, 'os.version', SCHEMA_TRACING.resource_tag_type()),
    (43, 'device.id', SCHEMA_TRACING.resource_tag_type()),
    (44, 'device.model.identifier', SCHEMA_TRACING.resource_tag_type()),
    (45, 'device.model.name', SCHEMA_TRACING.resource_tag_type()),
    (46, 'cloud.provider', SCHEMA_TRACING.resource_tag_type()),
    (47, 'cloud.account.id', SCHEMA_TRACING.resource_tag_type()),
    (48, 'cloud.region', SCHEMA_TRACING.resource_tag_type()),
    (49, 'cloud.availability_zone', SCHEMA_TRACING.resource_tag_type()),
    (50, 'cloud.platform', SCHEMA_TRACING.resource_tag_type()),
    (51, 'deployment.environment', SCHEMA_TRACING.resource_tag_type()),
    (52, 'k8s.cluster', SCHEMA_TRACING.resource_tag_type()),
    (53, 'k8s.node.name', SCHEMA_TRACING.resource_tag_type()),
    (54, 'k8s.node.uid', SCHEMA_TRACING.resource_tag_type()),
    (55, 'k8s.namespace.name', SCHEMA_TRACING.resource_tag_type()),
    (56, 'k8s.pod.uid', SCHEMA_TRACING.resource_tag_type()),
    (57, 'k8s.pod.name', SCHEMA_TRACING.resource_tag_type()),
    (58, 'k8s.container.name', SCHEMA_TRACING.resource_tag_type()),
    (59, 'k8s.replicaset.uid', SCHEMA_TRACING.resource_tag_type()),
    (60, 'k8s.replicaset.name', SCHEMA_TRACING.resource_tag_type()),
    (61, 'k8s.deployment.uid', SCHEMA_TRACING.resource_tag_type()),
    (62, 'k8s.deployment.name', SCHEMA_TRACING.resource_tag_type()),
    (63, 'k8s.statefulset.uid', SCHEMA_TRACING.resource_tag_type()),
    (64, 'k8s.statefulset.name', SCHEMA_TRACING.resource_tag_type()),
    (65, 'k8s.daemonset.uid', SCHEMA_TRACING.resource_tag_type()),
    (66, 'k8s.daemonset.name', SCHEMA_TRACING.resource_tag_type()),
    (67, 'k8s.job.uid', SCHEMA_TRACING.resource_tag_type()),
    (68, 'k8s.job.name', SCHEMA_TRACING.resource_tag_type()),
    (69, 'k8s.cronjob.uid', SCHEMA_TRACING.resource_tag_type()),
    (70, 'k8s.cronjob.name', SCHEMA_TRACING.resource_tag_type()),
    (71, 'net.transport', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (72, 'net.peer.ip', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (73, 'net.peer.port', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (74, 'net.peer.name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (75, 'net.host.ip', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (76, 'net.host.port', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (77, 'net.host.name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (78, 'net.host.connection.type', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (79, 'net.host.connection.subtype', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (80, 'net.host.carrier.name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (81, 'net.host.carrier.mcc', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (82, 'net.host.carrier.mnc', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (83, 'net.host.carrier.icc', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (84, 'peer.service', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (85, 'enduser.id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (86, 'enduser.role', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (87, 'enduser.scope', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (88, 'thread.id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (89, 'thread.name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (90, 'code.function', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (91, 'code.namespace', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (92, 'code.filepath', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (93, 'code.lineno', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (94, 'http.method', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (95, 'http.url', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (96, 'http.target', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (97, 'http.host', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (98, 'http.scheme', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (99, 'http.status_code', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (100, 'http.flavor', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (101, 'http.user_agent', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (102, 'http.request_content_length', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (103, 'http.request_content_length_uncompressed', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (104, 'http.response_content_length', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (105, 'http.response_content_length_uncompressed', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (106, 'http.server_name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (107, 'http.route', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (108, 'http.client_ip', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (109, 'db.system', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (110, 'db.connection_string', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (111, 'db.user', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (112, 'db.jdbc.driver_classname', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (113, 'db.mssql.instance_name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (114, 'db.name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (115, 'db.statement', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (116, 'db.operation', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (117, 'db.hbase.namespace', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (118, 'db.redis.database_index', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (119, 'db.mongodb.collection', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (120, 'db.sql.table', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (121, 'db.cassandra.keyspace', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (122, 'db.cassandra.page_size', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (123, 'db.cassandra.consistency_level', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (124, 'db.cassandra.table', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (125, 'db.cassandra.idempotence', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (126, 'db.cassandra.speculative_execution_count', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (127, 'db.cassandra.coordinator.id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (128, 'db.cassandra.coordinator.dc', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (129, 'rpc.system', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (130, 'rpc.service', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (131, 'rpc.method', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (132, 'rpc.grpc.status_code', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (133, 'message.type', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (134, 'message.id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (135, 'message.compressed_size', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (136, 'message.uncompressed_size', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (137, 'rpc.jsonrpc.version', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (138, 'rpc.jsonrpc.request_id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (139, 'rpc.jsonrpc.error_code', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (140, 'rpc.jsonrpc.error_message', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (141, 'messaging.system', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (142, 'messaging.destination', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (143, 'messaging.destination_kind', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (144, 'messaging.temp_destination', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (145, 'messaging.protocol', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (146, 'messaging.url', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (147, 'messaging.message_id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (148, 'messaging.conversation_id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (149, 'messaging.message_payload_size_bytes', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (150, 'messaging.message_payload_compressed_size_bytes', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (151, 'messaging.operation', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (152, 'messaging.consumer_id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (153, 'messaging.rabbitmq.routing_key', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (154, 'messaging.kafka.message_key', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (155, 'messaging.kafka.consumer_group', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (156, 'messaging.kafka.client_id', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (157, 'messaging.kafka.partition', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (158, 'messaging.kafka.tombstone', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (159, 'faas.trigger', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (160, 'faas.speculative_execution_count', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (161, 'faas.coldstart', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (162, 'faas.invoked_name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (163, 'faas.invoked_provider', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (164, 'faas.invoked_region', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (165, 'faas.document.collection', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (166, 'faas.document.operation', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (167, 'faas.document.time', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (168, 'faas.document.name', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (169, 'faas.time', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (170, 'faas.cron', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (171, 'exception.type', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (172, 'exception.message', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (173, 'exception.stacktrace', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type()),
    (174, 'exception.escaped', SCHEMA_TRACING.span_tag_type() | SCHEMA_TRACING.event_tag_type() | SCHEMA_TRACING.link_tag_type())
;
SELECT setval('SCHEMA_TRACING.tag_key_id_seq', 1000);
